### ISSUE TITLE
Svg does not render

### ISSUE THREAD

**Issue by doofin** [raquo/Laminar#31] opened 2018-08-09 08:37 UTC
```scala
import com.raquo.laminar.api.L._
import com.raquo.laminar.api.L.{svg => s}


    div(
      s.svg(
        s.height := "800",
        s.width := "500",
        s.circle(
          s.cx := "100",
          s.r := "30",
          s.fill := "red"
        )
      )
    )
```
svg is present in chrom dev tool but is not showed

**Comment by raquo** [comment] 2018-08-14 07:54
Hrm, looks like this is caused by Scala DOM Builder passing an incorrect XML namespace when setting SVG attributes. Too bad we can't test such things with jsdom...

Desired behaviour is explained here: https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course#Scripting_in_namespaced_XML

We should be passing `null` as the XML namespace for most attributes in `setAttributeNS` calls.

However, `xlinkTitle` and `xlinkHref` svg attributes will need a different SVG namespace specified.

I need to figure out a good way to deal with this. As a temporary workaround you can probably replace `svgNamespaceUri` with `null` on this line in SDB: https://github.com/raquo/scala-dom-builder/blob/af7c63b8deb23ce7c1db7fde87f8068ad79fe8b4/js/src/main/scala/com/raquo/dombuilder/jsdom/domapi/JsSvgElementApi.scala#L23 I haven't had a chance to test this fix in SDB / Laminar context, but a simple js fiddle indicates that this should work.

Thanks for reporting this. I'm really swamped right now, I'll try to get this fixed within a couple weeks.

**Comment by doofin** [comment] 2018-08-14 08:08
Thanks!  This kind of behavior is quite annoying: ``` In other words, although the attributes belong to the namespace of the tag, you do not use the tag's namespace name. Instead, you must use null as the namespace name for unqualified (prefixless) attributes```

**Comment by doofin** [comment] 2018-08-14 08:38
https://github.com/raquo/scala-dom-builder/pull/5

**Closed** 2018-08-23 08:29 UTC
Labels: Scala DOM Builder, bug
